[package]
name = "rusted-nostr-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bech32 = "0.9.1"
hex = "0.4.3"
rand = "0.8.5"
secp256k1 = "0.27.0"
tokio = "1.26.0"
